# Generated by Django 2.1.7 on 2019-09-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNnumber', models.CharField(max_length=500)),
                ('CircuitID', models.IntegerField(default=0)),
                ('Division', models.CharField(max_length=200)),
                ('TaxName', models.CharField(max_length=500)),
                ('FullAddress', models.CharField(max_length=2000)),
                ('GSTNo', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('BillingDate_From', models.DateTimeField()),
                ('City', models.CharField(max_length=500)),
                ('PremiseName', models.CharField(max_length=500)),
                ('processing_status', models.CharField(max_length=500)),
                ('CustomerID', models.CharField(max_length=500)),
                ('PremiseNo', models.CharField(max_length=500)),
                ('BillingDate_TO', models.DateTimeField()),
                ('Speed', models.CharField(max_length=500)),
                ('Remarks', models.CharField(max_length=2000)),
                ('InvoiceDate', models.DateTimeField()),
                ('ServiceType', models.CharField(max_length=500)),
            ],
        ),
    ]
