user_auth_info_from: file # OSENV or file , leave it as file
user_auth_info_file_location: /home/ubuntu/tlclient/user_settings.ini # change this location to users home dir
fernet_key_file: /home/ubuntu/tlclient/prod_farnetkeys
#tl_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYV9y94je6Z9N0iarh0xNrE3IFGrdktV2TLfI5h60hfd9yO7L9BZtd94/r2L6VGFSwT/dhBR//CwkIuue3RW23nbm2OIYsmsijBSHtm1/2tw/0g0UbbneM9vFt9ciCjdq3W4VY8I6iQ7s7v98qrtRxhqLc/rH2MmfERhQaMQPaSnMaB59R46xCtCnsJ+OoZs5XhGOJXJz8YKuCw4gUs4soRMb7+k7F4wADseoYuwtVLoEmSC+ikbmPZNWOY18HxNrSVJOvMH2sCoewY6/GgS/5s1zlWBwV/F0UvmKoCTf0KcNHcdzXbeDU9/PkGU/uItRYVfXIWYJVQZBveu7BYJDR bhujay@DESKTOP-DTA1VEB
ssl_verify: False # leave it as is
tl_user: user1
tl_url: https://10.174.112.122:5001
ssl_verify: False
tl_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDme8B1BT9akm26y6j2osynrXPRPsbBN+RQfVu1yIFQThMzucoGvANyOBfZdNCQN2O74XiyhsnSW80h3/aoB3D7lM7eJwa6mT8vMw7h7tcIG+WoyO3B4kK3+jceQm7qeoSXzbotmDLnub6G9v6JEQiijts2yQElW1S6Jj2+hfaZigwN2dXhBb7otqH9DBk4uNoLAo/XUxbE8XCAoO99IjMHqaByhD2wb26YSbqgqAZ9b0hGtVON50+9zhrRPc3q3a3Y8L320YJEEDzO2JTR4WjNd0wHj/o3YFe7p6cW5iIOSTJ5b7CZm/kgKPQZ43WNWmJBOIhlrGjo9IMYqXRsbiPj ubuntu@tokenleader

linkInventory:
  url_type: endpoint_url_external
  ssl_enabled: no
  ssl_verify: no

